services:
  db:
    image: pgvector/pgvector:pg17

    container_name: eih-postgres

    environment:
      POSTGRES_DB: eih
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
